#!/usr/bin/env bash
# Conductor Phase 0 — Start inference engine
# Sources hardware profile from detect-hardware.sh if available.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ── Source hardware profile (generated by detect-hardware.sh) ───────
PROFILE="$SCRIPT_DIR/hardware-profile.env"
if [[ -f "$PROFILE" ]]; then
  # shellcheck source=/dev/null
  source "$PROFILE"
  echo "[inference] Loaded hardware profile: $PROFILE"
else
  echo "[inference] No hardware-profile.env found — using defaults."
  echo "[inference] Run ./detect-hardware.sh to auto-configure for your hardware."
fi

# ── Resolve settings (profile overrides → defaults) ─────────────────
MODEL_PATH="${CONDUCTOR_MODEL_PATH:-./models/qwen3-coder-next/Qwen3-Coder-Next-UD-Q4_K_XL.gguf}"
LLAMA_BIN="${CONDUCTOR_LLAMA_BIN:-./build/bin/llama-server}"
N_GPU_LAYERS="${CONDUCTOR_N_GPU_LAYERS:-99}"
GPU_OFFLOAD="${CONDUCTOR_GPU_OFFLOAD:-}"
N_PARALLEL="${CONDUCTOR_N_PARALLEL:-5}"
CTX_SIZE="${CONDUCTOR_CTX_SIZE:-32768}"
BATCH_SIZE="${CONDUCTOR_BATCH_SIZE:-4096}"
UBATCH_SIZE="${CONDUCTOR_UBATCH_SIZE:-4096}"
CACHE_TYPE_K="${CONDUCTOR_CACHE_TYPE_K:-q8_0}"
CACHE_TYPE_V="${CONDUCTOR_CACHE_TYPE_V:-q8_0}"
CACHE_REUSE="${CONDUCTOR_CACHE_REUSE:-256}"
PORT="${CONDUCTOR_INFERENCE_PORT:-8080}"

# ── Preflight checks ───────────────────────────────────────────────
if [[ ! -x "$LLAMA_BIN" ]] && [[ ! -L "$LLAMA_BIN" ]]; then
  echo "[ERROR] llama-server not found at: $LLAMA_BIN"
  echo "        Run ./setup.sh to build it, or set CONDUCTOR_LLAMA_BIN."
  exit 1
fi

if [[ ! -f "$MODEL_PATH" ]]; then
  echo "[ERROR] Model file not found at: $MODEL_PATH"
  echo "        Run ./setup.sh to download it, or set CONDUCTOR_MODEL_PATH."
  exit 1
fi

mkdir -p "$SCRIPT_DIR/data/kv-cache"

echo "[inference] Model:       $MODEL_PATH"
echo "[inference] Binary:      $LLAMA_BIN"
echo "[inference] GPU layers:  $N_GPU_LAYERS"
echo "[inference] Parallel:    $N_PARALLEL"
echo "[inference] Context:     $CTX_SIZE"
echo "[inference] Port:        $PORT"

# ── Build command ───────────────────────────────────────────────────
CMD=(
  "$LLAMA_BIN"
  --model "$MODEL_PATH"
  --host 0.0.0.0
  --port "$PORT"
  --n-gpu-layers "$N_GPU_LAYERS"
)

# GPU offload overrides (e.g. "-ot .ffn_.*_exps.=CPU")
if [[ -n "$GPU_OFFLOAD" ]]; then
  # Split by semicolons for multiple -ot flags
  IFS=';' read -ra OT_PARTS <<< "$GPU_OFFLOAD"
  for ot in "${OT_PARTS[@]}"; do
    [[ -n "$ot" ]] && CMD+=(-ot "$ot")
  done
else
  # Default: offload MoE expert FFNs to CPU (P40 VRAM management)
  CMD+=(-ot ".ffn_.*_exps.=CPU")
fi

CMD+=(
  -np "$N_PARALLEL"
  --slot-save-path ./data/kv-cache
  --ctx-size "$CTX_SIZE"
  -b "$BATCH_SIZE"
  -ub "$UBATCH_SIZE"
  --cache-type-k "$CACHE_TYPE_K"
  --cache-type-v "$CACHE_TYPE_V"
  --cache-reuse "$CACHE_REUSE"
  -sps 0.3
  --jinja
  --temp 1.0
  --top-p 0.95
  --top-k 40
  --min-p 0.01
)

exec "${CMD[@]}"
