export const browserCoreExamples = [
  "maistro browser status",
  "maistro browser start",
  "maistro browser stop",
  "maistro browser tabs",
  "maistro browser open https://example.com",
  "maistro browser focus abcd1234",
  "maistro browser close abcd1234",
  "maistro browser screenshot",
  "maistro browser screenshot --full-page",
  "maistro browser screenshot --ref 12",
  "maistro browser snapshot",
  "maistro browser snapshot --format aria --limit 200",
  "maistro browser snapshot --efficient",
  "maistro browser snapshot --labels",
];

export const browserActionExamples = [
  "maistro browser navigate https://example.com",
  "maistro browser resize 1280 720",
  "maistro browser click 12 --double",
  'maistro browser type 23 "hello" --submit',
  "maistro browser press Enter",
  "maistro browser hover 44",
  "maistro browser drag 10 11",
  "maistro browser select 9 OptionA OptionB",
  "maistro browser upload /tmp/maistro/uploads/file.pdf",
  'maistro browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "maistro browser dialog --accept",
  'maistro browser wait --text "Done"',
  "maistro browser evaluate --fn '(el) => el.textContent' --ref 7",
  "maistro browser console --level error",
  "maistro browser pdf",
];
