#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${MAISTRO_INSTALL_E2E_IMAGE:-${MAISTRO_INSTALL_E2E_IMAGE:-maistro-install-e2e:local}}"
INSTALL_URL="${MAISTRO_INSTALL_URL:-${MAISTRO_INSTALL_URL:-https://maistro.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
MAISTRO_E2E_MODELS="${MAISTRO_E2E_MODELS:-${MAISTRO_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e MAISTRO_INSTALL_URL="$INSTALL_URL" \
  -e MAISTRO_INSTALL_TAG="${MAISTRO_INSTALL_TAG:-${MAISTRO_INSTALL_TAG:-latest}}" \
  -e MAISTRO_E2E_MODELS="$MAISTRO_E2E_MODELS" \
  -e MAISTRO_INSTALL_E2E_PREVIOUS="${MAISTRO_INSTALL_E2E_PREVIOUS:-${MAISTRO_INSTALL_E2E_PREVIOUS:-}}" \
  -e MAISTRO_INSTALL_E2E_SKIP_PREVIOUS="${MAISTRO_INSTALL_E2E_SKIP_PREVIOUS:-${MAISTRO_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
